// Hand-curated study-guide content: equations, landmark studies, exam prompts, references.
// Lexicon terms and timestamps come from the chapter files at build time.
const v = (s) => `<i>${s}</i>`;

export const CHAPTERS = {
  pop: {
    equations: [
      ['Exponential growth', `d${v('N')}/d${v('t')} = ${v('rN')}, &nbsp; ${v('N')}(${v('t')}) = ${v('N')}<sub>0</sub>${v('e')}<sup>${v('rt')}</sup>, &nbsp; ${v('r')} = ${v('b')} − ${v('d')}, &nbsp; ${v('t')}<sub>d</sub> = ln 2 / ${v('r')}`],
      ['Geometric growth', `${v('N')}<sub>${v('t')}+1</sub> = λ${v('N')}<sub>${v('t')}</sub>, &nbsp; λ = ${v('e')}<sup>${v('r')}</sup>`],
      ['Logistic growth', `d${v('N')}/d${v('t')} = ${v('rN')}(1 − ${v('N')}/${v('K')}); &nbsp; MSY = ${v('rK')}/4 at ${v('N')} = ${v('K')}/2`],
      ['Delayed logistic (Hutchinson)', `d${v('N')}/d${v('t')} = ${v('rN')}(${v('t')})[1 − ${v('N')}(${v('t')} − τ)/${v('K')}]: monotonic if ${v('r')}τ &lt; 1/${v('e')}; damped if 1/${v('e')} &lt; ${v('r')}τ &lt; π/2; limit cycle if ${v('r')}τ &gt; π/2`],
      ['Logistic map (May)', `${v('x')}<sub>${v('t')}+1</sub> = ${v('r')}${v('x')}<sub>${v('t')}</sub>(1 − ${v('x')}<sub>${v('t')}</sub>): 2-cycle at ${v('r')} = 3, 4-cycle at ≈ 3.449, chaos beyond ≈ 3.57`],
      ['Life table', `${v('R')}<sub>0</sub> = Σ ${v('l')}<sub>${v('x')}</sub>${v('m')}<sub>${v('x')}</sub>; &nbsp; ${v('G')} = Σ ${v('x l')}<sub>${v('x')}</sub>${v('m')}<sub>${v('x')}</sub> / ${v('R')}<sub>0</sub>; &nbsp; ${v('r')} ≈ ln ${v('R')}<sub>0</sub> / ${v('G')}`],
      ['Matrix model', `<b>n</b>(${v('t')}+1) = <b>A n</b>(${v('t')}); λ = dominant eigenvalue; <b>w</b> = stable stage distribution; <b>v</b> = reproductive values; sensitivity ${v('s')}<sub>${v('ij')}</sub> = ${v('v')}<sub>${v('i')}</sub>${v('w')}<sub>${v('j')}</sub>/⟨<b>v</b>,<b>w</b>⟩; elasticity ${v('e')}<sub>${v('ij')}</sub> = (${v('a')}<sub>${v('ij')}</sub>/λ)${v('s')}<sub>${v('ij')}</sub>`],
      ['Variable environments', `λ<sub>G</sub> = (Π λ<sub>${v('t')}</sub>)<sup>1/${v('T')}</sup> ≤ λ̄; &nbsp; ln λ<sub>G</sub> ≈ ln λ̄ − σ<sup>2</sup>/(2λ̄<sup>2</sup>)`],
    ],
    studies: [
      ['Hutchinson 1948', 'Theory', 'Time lags in density dependence can generate oscillations.'],
      ['May 1976', 'Logistic map', 'Simple deterministic models produce period doubling and chaos.'],
      ['Crouse, Crowder & Caswell 1987', 'Loggerhead sea turtle', 'λ most elastic to large-juvenile survival; supported turtle excluder devices over egg protection alone.'],
      ['Shaffer 1981', 'Minimum viable population', 'Defined MVP via a persistence probability and time horizon (e.g., 99% for 1000 years).'],
      ['Gilpin & Soulé 1986', 'Extinction vortex', 'Genetic and demographic processes reinforce declines in small populations.'],
      ['Grime 1977', 'Plant strategies', 'C-S-R triangle of competitors, stress-tolerators, and ruderals.'],
    ],
    prompts: [
      'Derive maximum sustainable yield from the logistic model. Why is harvesting at MSY risky when the environment varies?',
      'Show with a numerical example why variance in λ lowers long-run growth even when mean λ exceeds 1.',
      'Distinguish sensitivity from elasticity. How did elasticity analysis change sea turtle conservation?',
      'How does a strong Allee effect change the logic of minimum viable population size?',
    ],
  },
  niche: {
    equations: [
      ['MacArthur–Levins overlap', `α<sub>${v('ij')}</sub> = Σ<sub>${v('k')}</sub> ${v('p')}<sub>${v('ik')}</sub>${v('p')}<sub>${v('jk')}</sub> / Σ<sub>${v('k')}</sub> ${v('p')}<sub>${v('ik')}</sub><sup>2</sup> &nbsp; (${v('p')} = proportional use of resource ${v('k')})`],
      ['Pianka overlap', `${v('O')}<sub>${v('jk')}</sub> = Σ ${v('p')}<sub>${v('ij')}</sub>${v('p')}<sub>${v('ik')}</sub> / √(Σ ${v('p')}<sub>${v('ij')}</sub><sup>2</sup> Σ ${v('p')}<sub>${v('ik')}</sub><sup>2</sup>)`],
      ['Limiting similarity', `coexistence requires roughly ${v('d')}/${v('w')} ≳ 1 (separation of means / utilization width)`],
      ['Requirement niche (ZNGI)', `the set of resource levels where (1/${v('N')}) d${v('N')}/d${v('t')} = ${v('f')}(${v('R')}<sub>1</sub>, ${v('R')}<sub>2</sub>) − ${v('m')} = 0`],
    ],
    studies: [
      ['Grinnell 1917', 'California thrasher', 'Niche as the habitat conditions a species requires.'],
      ['Elton 1927', 'Animal Ecology', 'Niche as functional role: relations to food and enemies.'],
      ['Hutchinson 1957', 'Theory', 'Niche as an n-dimensional hypervolume; fundamental vs realized niches.'],
      ['Connell 1961', 'Barnacles, Isle of Cumbrae', 'Competition from Balanus sets the lower limit of Chthamalus; desiccation sets Balanus’s upper limit.'],
      ['MacArthur 1958', 'Spruce-woods warblers', 'Five congeners partition foraging zones and behavior within trees.'],
      ['Lack 1947; Grant & Grant 2006', 'Darwin’s finches', 'Character displacement in beak size in sympatry.'],
      ['Chase & Leibold 2003', 'Theory', 'Niche = requirements (ZNGIs) + impacts (consumption vectors).'],
      ['Soberón & Peterson 2005', 'Distribution modeling', 'BAM diagram: Abiotic, Biotic, and Movement constraints on distributions.'],
    ],
    prompts: [
      'Compare Grinnellian, Eltonian, and Hutchinsonian niches. Which does a species distribution model estimate, and why?',
      'Design an experiment that separates the fundamental from the realized niche of two plants along a moisture gradient.',
      'What evidence would distinguish character displacement from alternative explanations (cf. Schluter & McPhail 1992)?',
      'Explain how requirement and impact niches together predict the outcome of competition.',
    ],
  },
  comp: {
    equations: [
      ['Lotka–Volterra competition', `d${v('N')}<sub>1</sub>/d${v('t')} = ${v('r')}<sub>1</sub>${v('N')}<sub>1</sub>(${v('K')}<sub>1</sub> − ${v('N')}<sub>1</sub> − α<sub>12</sub>${v('N')}<sub>2</sub>)/${v('K')}<sub>1</sub>; &nbsp; d${v('N')}<sub>2</sub>/d${v('t')} = ${v('r')}<sub>2</sub>${v('N')}<sub>2</sub>(${v('K')}<sub>2</sub> − ${v('N')}<sub>2</sub> − α<sub>21</sub>${v('N')}<sub>1</sub>)/${v('K')}<sub>2</sub>`],
      ['Outcomes', `species 1 wins: ${v('K')}<sub>1</sub> &gt; ${v('K')}<sub>2</sub>/α<sub>21</sub> and ${v('K')}<sub>1</sub>/α<sub>12</sub> &gt; ${v('K')}<sub>2</sub> · species 2 wins: reverse · stable coexistence: ${v('K')}<sub>1</sub> &lt; ${v('K')}<sub>2</sub>/α<sub>21</sub> and ${v('K')}<sub>2</sub> &lt; ${v('K')}<sub>1</sub>/α<sub>12</sub> (α<sub>12</sub> &lt; ${v('K')}<sub>1</sub>/${v('K')}<sub>2</sub>, α<sub>21</sub> &lt; ${v('K')}<sub>2</sub>/${v('K')}<sub>1</sub>) · unstable (priority effects): ${v('K')}<sub>1</sub> &gt; ${v('K')}<sub>2</sub>/α<sub>21</sub> and ${v('K')}<sub>2</sub> &gt; ${v('K')}<sub>1</sub>/α<sub>12</sub>`],
      ['Resource competition (Tilman)', `d${v('N')}/d${v('t')} = ${v('N')}[${v('f')}(${v('R')}) − ${v('m')}]; ${v('R')}* solves ${v('f')}(${v('R')}*) = ${v('m')}; with Monod uptake ${v('f')} = μ<sub>max</sub>${v('R')}/(${v('K')}<sub>s</sub> + ${v('R')}), ${v('R')}* = ${v('m K')}<sub>s</sub>/(μ<sub>max</sub> − ${v('m')})`],
      ['Modern coexistence (Chesson)', `coexistence when ρ &lt; κ<sub>1</sub>/κ<sub>2</sub> &lt; 1/ρ; niche difference = 1 − ρ; fitness ratio = κ<sub>1</sub>/κ<sub>2</sub>; invasion criterion: r̄<sub>${v('i')}</sub> &gt; 0 when rare`],
    ],
    studies: [
      ['Gause 1934', 'Paramecium', 'Competitive exclusion in laboratory cultures.'],
      ['Park 1954', 'Tribolium flour beetles', 'Climate-dependent outcomes and priority effects.'],
      ['Tilman 1977', 'Freshwater diatoms', 'Phosphate and silicate ratios predicted competitive outcomes (R* and resource ratios).'],
      ['Wedin & Tilman 1993', 'Prairie grasses', 'Lowest R* for soil nitrogen predicted the winner.'],
      ['Schoener 1983', 'Review of field experiments', 'Competition common in field experiments; six mechanisms of competition.'],
      ['Holt 1977', 'Theory', 'Apparent competition through a shared predator.'],
      ['Janzen 1970; Connell 1971', 'Tropical trees', 'Specialist enemies near parents promote diversity (Janzen–Connell).'],
      ['Chesson 2000', 'Theory', 'Stabilizing vs equalizing mechanisms; storage effect; relative nonlinearity.'],
      ['Hutchinson 1961', 'Phytoplankton', 'Paradox of the plankton.'],
    ],
    prompts: [
      'Draw the four Lotka–Volterra isocline configurations and state the condition for each outcome.',
      'Why does the species with the lowest R* win? Which assumptions does the rule require?',
      'Distinguish stabilizing from equalizing mechanisms, with a field example of each.',
      'How would you test for apparent competition in a field system?',
    ],
  },
  pred: {
    equations: [
      ['Lotka–Volterra predator–prey', `d${v('N')}/d${v('t')} = ${v('rN')} − ${v('aNP')}; &nbsp; d${v('P')}/d${v('t')} = ${v('caNP')} − ${v('mP')}; &nbsp; isoclines ${v('N')}* = ${v('m')}/(${v('ca')}), ${v('P')}* = ${v('r')}/${v('a')}`],
      ['Functional responses (Holling)', `Type II: ${v('f')}(${v('N')}) = ${v('aN')}/(1 + ${v('ahN')}) → 1/${v('h')} as ${v('N')} → ∞; &nbsp; Type III: ${v('f')}(${v('N')}) = ${v('aN')}<sup>2</sup>/(1 + ${v('ahN')}<sup>2</sup>)`],
      ['Rosenzweig–MacArthur', `d${v('N')}/d${v('t')} = ${v('rN')}(1 − ${v('N')}/${v('K')}) − ${v('aNP')}/(1 + ${v('ahN')}); &nbsp; d${v('P')}/d${v('t')} = ${v('caNP')}/(1 + ${v('ahN')}) − ${v('mP')}`],
      ['Nicholson–Bailey', `${v('H')}<sub>${v('t')}+1</sub> = λ${v('H')}<sub>${v('t')}</sub>${v('e')}<sup>−${v('aP')}<sub>${v('t')}</sub></sup>; &nbsp; ${v('P')}<sub>${v('t')}+1</sub> = ${v('cH')}<sub>${v('t')}</sub>(1 − ${v('e')}<sup>−${v('aP')}<sub>${v('t')}</sub></sup>)`],
      ['Marginal value theorem', `leave when ${v('g')}′(${v('t')}*) = ${v('g')}(${v('t')}*)/(τ + ${v('t')}*), the long-term average intake rate including travel time τ`],
      ['Diet model', `add prey type ${v('i')} (ranked by ${v('E')}/${v('h')}) if ${v('E')}<sub>${v('i')}</sub>/${v('h')}<sub>${v('i')}</sub> &gt; Σ<sub>${v('j')}&lt;${v('i')}</sub> λ<sub>${v('j')}</sub>${v('E')}<sub>${v('j')}</sub> / (1 + Σ<sub>${v('j')}&lt;${v('i')}</sub> λ<sub>${v('j')}</sub>${v('h')}<sub>${v('j')}</sub>)`],
    ],
    studies: [
      ['Gause 1934', 'Paramecium & Didinium', 'Predator eliminated prey unless refuges or immigration were added.'],
      ['Huffaker 1958', 'Mites on oranges', 'Persistence required spatial complexity and dispersal barriers.'],
      ['Holling 1959', 'Functional responses', 'Types I–III; the disc equation and handling time.'],
      ['Rosenzweig 1971', 'Theory', 'Paradox of enrichment.'],
      ['Krebs et al. 1995; Sheriff et al. 2009', 'Snowshoe hare, Kluane (Yukon)', 'Food and predation jointly drive the cycle; predator-induced stress lowers reproduction.'],
      ['Paine 1966, 1969', 'Pisaster, Washington coast', 'Keystone predation maintains diversity (15 → 8 species after removal).'],
      ['Hairston, Smith & Slobodkin 1960', 'Theory', 'Green world hypothesis: predators limit herbivores.'],
      ['Estes et al. 1998', 'Aleutian kelp forests', 'Orca predation on otters released urchins and collapsed kelp.'],
      ['Crooks & Soulé 1999', 'Southern California scrub', 'Coyote loss led to mesopredator release and bird declines.'],
      ['Zanette et al. 2011', 'Song sparrows', 'Predator playback alone reduced annual offspring by ~40%.'],
      ['Charnov 1976', 'Theory', 'Marginal value theorem for patch residence.'],
    ],
    prompts: [
      'Why is the Lotka–Volterra predator–prey model structurally unstable? List modifications that stabilize it.',
      'Explain the paradox of enrichment with the Rosenzweig–MacArthur isocline diagram.',
      'Contrast consumptive and non-consumptive effects of predators. How could you separate them experimentally?',
      'Under what conditions should a trophic cascade propagate to primary producers?',
    ],
  },
  isl: {
    equations: [
      ['Species–area relationship', `${v('S')} = ${v('cA')}<sup>${v('z')}</sup>; &nbsp; log ${v('S')} = log ${v('c')} + ${v('z')} log ${v('A')}; &nbsp; islands ${v('z')} ≈ 0.20–0.35, mainland nested samples ≈ 0.12–0.17`],
      ['Linear equilibrium model', `${v('I')}(${v('S')}) = ${v('I')}<sub>0</sub>(1 − ${v('S')}/${v('P')}), ${v('E')}(${v('S')}) = ${v('E')}<sub>0</sub>${v('S')}/${v('P')} &nbsp;⇒&nbsp; Ŝ = ${v('I')}<sub>0</sub>${v('P')}/(${v('I')}<sub>0</sub> + ${v('E')}<sub>0</sub>), &nbsp; turnover ${v('T')} = ${v('I')}<sub>0</sub>${v('E')}<sub>0</sub>/(${v('I')}<sub>0</sub> + ${v('E')}<sub>0</sub>)`],
      ['Darlington’s rule', `with ${v('z')} ≈ 0.3, a tenfold loss of area leaves 10<sup>−0.3</sup> ≈ 0.5 of the species`],
    ],
    studies: [
      ['MacArthur & Wilson 1963, 1967', 'Theory', 'Equilibrium theory: richness balances immigration and extinction.'],
      ['Simberloff & Wilson 1969', 'Mangrove islets, Florida Keys', 'Arthropods recolonized to near pre-defaunation richness within ~1 year, with turnover.'],
      ['Brown & Kodric-Brown 1977', 'Arthropods on thistles', 'Rescue effect: immigration lowers extinction on near islands.'],
      ['Lomolino 1990', 'Mammals on islands', 'Target-area effect: larger islands receive more immigrants.'],
      ['Diamond 1975; Simberloff & Abele 1976', 'Reserve design', 'The SLOSS debate.'],
      ['Newmark 1987', 'Western North American parks', 'Mammal extinctions since establishment, greatest in small parks.'],
      ['Whittaker et al. 2008', 'Oceanic islands', 'General dynamic model: island age, area, and in-situ speciation.'],
    ],
    prompts: [
      'Draw the MacArthur–Wilson diagram for near/far and large/small islands; predict richness and turnover for each.',
      'What did the Simberloff–Wilson defaunation experiment demonstrate, and what were its limitations?',
      'Define extinction debt and explain how you would estimate it for a fragmented landscape.',
      'Argue both sides of SLOSS for a reserve network in your own study system.',
    ],
  },
  meta: {
    equations: [
      ['Levins model', `d${v('p')}/d${v('t')} = ${v('cp')}(1 − ${v('p')}) − ${v('ep')}; &nbsp; ${v('p')}* = 1 − ${v('e')}/${v('c')}; persistence requires ${v('c')} &gt; ${v('e')}`],
      ['Habitat destruction', `d${v('p')}/d${v('t')} = ${v('cp')}(1 − ${v('D')} − ${v('p')}) − ${v('ep')}; &nbsp; ${v('p')}* = 1 − ${v('D')} − ${v('e')}/${v('c')}; extinction threshold at ${v('D')} = 1 − ${v('e')}/${v('c')}`],
      ['Incidence function model (Hanski)', `${v('J')}<sub>${v('i')}</sub> = ${v('C')}<sub>${v('i')}</sub>/(${v('C')}<sub>${v('i')}</sub> + ${v('E')}<sub>${v('i')}</sub> − ${v('C')}<sub>${v('i')}</sub>${v('E')}<sub>${v('i')}</sub>); &nbsp; ${v('E')}<sub>${v('i')}</sub> = min(1, ${v('e')}/${v('A')}<sub>${v('i')}</sub><sup>${v('x')}</sup>); &nbsp; ${v('C')}<sub>${v('i')}</sub> = ${v('S')}<sub>${v('i')}</sub><sup>2</sup>/(${v('S')}<sub>${v('i')}</sub><sup>2</sup> + ${v('y')}<sup>2</sup>)`],
      ['Connectivity', `${v('S')}<sub>${v('i')}</sub> = Σ<sub>${v('j')}≠${v('i')}</sub> ${v('p')}<sub>${v('j')}</sub> ${v('e')}<sup>−α${v('d')}<sub>${v('ij')}</sub></sup> ${v('A')}<sub>${v('j')}</sub><sup>${v('b')}</sup>`],
      ['Source–sink', `sources: λ &gt; 1 (net exporters); sinks: λ &lt; 1 (persist only with immigration)`],
    ],
    studies: [
      ['Levins 1969', 'Agricultural pests', 'Metapopulation concept and patch-occupancy model.'],
      ['Harrison 1991', 'Review', 'Types: classic, mainland–island, patchy, nonequilibrium.'],
      ['Pulliam 1988', 'Theory', 'Sources, sinks, and population regulation.'],
      ['Hanski 1994, 1998', 'Glanville fritillary, Åland', 'Incidence function model; occupancy predicted by area and connectivity.'],
      ['Moran 1953', 'Canadian lynx', 'Correlated weather synchronizes separate populations (Moran effect).'],
      ['Tilman, May, Lehman & Nowak 1994', 'Theory', 'Habitat destruction and extinction debt; best competitors lost first.'],
      ['Schlaepfer, Runge & Sherman 2002', 'Review', 'Ecological and evolutionary traps.'],
    ],
    prompts: [
      'Derive p* for the Levins model and explain why a species can vanish while suitable habitat remains.',
      'Distinguish the main metapopulation types and give a real example of each.',
      'Why can abundance mislead about habitat quality? Include ecological traps in your answer.',
      'How does spatial synchrony affect metapopulation persistence, and what causes it?',
    ],
  },
  mc: {
    equations: [
      ['Whittaker’s partition', `γ = ᾱ × β (multiplicative); additive form γ = ᾱ + β<sub>add</sub>`],
      ['Turnover vs nestedness (Baselga)', `β<sub>SOR</sub> = β<sub>SIM</sub> (turnover) + β<sub>SNE</sub> (nestedness-resultant)`],
      ['Variation partitioning', `[${v('a')}] environment only + [${v('b')}] shared + [${v('c')}] space only + [${v('d')}] unexplained = 1 (adjusted ${v('R')}<sup>2</sup> from RDA)`],
    ],
    studies: [
      ['Whittaker 1960, 1972', 'Siskiyou Mountains vegetation', 'Introduced α, β, and γ diversity.'],
      ['Tilman 1994', 'Theory', 'Competition–colonization trade-off permits regional coexistence.'],
      ['Leibold et al. 2004', 'Synthesis', 'Metacommunity concept; four paradigms.'],
      ['Mouquet & Loreau 2003', 'Theory', 'Local diversity peaks at intermediate dispersal; β declines with dispersal.'],
      ['Cottenie 2005', 'Meta-analysis of 158 datasets', 'Variation partitioning across metacommunities; species sorting most common.'],
      ['Kraft et al. 2015', 'Critique', 'Competition can masquerade as environmental filtering.'],
    ],
    prompts: [
      'Contrast the four metacommunity paradigms by their assumptions about environmental heterogeneity and dispersal.',
      'Why is local diversity predicted to peak at intermediate dispersal rates?',
      'What can, and cannot, variation partitioning tell you about metacommunity processes?',
      'Partition γ into α and β for three sites with species {A,B,C}, {B,C,D}, and {D,E}.',
    ],
  },
  neu: {
    equations: [
      ['Fundamental biodiversity number', `θ = 2${v('J')}<sub>${v('M')}</sub>ν (metacommunity size × speciation rate); equals Fisher’s α at equilibrium`],
      ['Log-series (metacommunity)', `expected species with ${v('n')} individuals: ${v('S')}<sub>${v('n')}</sub> = θ${v('x')}<sup>${v('n')}</sup>/${v('n')}, with ${v('x')} close to 1`],
      ['Ewens sampling formula', `E[${v('S')}] = Σ<sub>${v('k')}=0</sub><sup>${v('J')}−1</sup> θ/(θ + ${v('k')})`],
      ['Immigration', `${v('m')} = probability a local death is replaced by an immigrant; Etienne’s ${v('I')} = ${v('m')}(${v('J')} − 1)/(1 − ${v('m')})`],
    ],
    studies: [
      ['Kimura 1968', 'Molecular evolution', 'Neutral theory of molecular evolution; drift of neutral alleles.'],
      ['Fisher, Corbet & Williams 1943', 'Butterflies, moths', 'Log-series distribution and Fisher’s α.'],
      ['Preston 1948, 1962', 'Birds, moths', 'Lognormal distribution in octaves; veil line.'],
      ['Hubbell 2001', 'Barro Colorado Island forest', 'Unified neutral theory; θ, m, zero-sum multinomial.'],
      ['Condit et al. 2002', 'Tropical forests, Panama and Amazonia', 'Distance decay of similarity tested against dispersal limitation.'],
      ['McGill 2003; Volkov et al. 2003', 'BCI and others', 'Debate over whether neutral SADs outperform the lognormal.'],
      ['Comita et al. 2010', 'Barro Colorado Island', 'Conspecific negative density dependence varies among species.'],
      ['Scheffer & van Nes 2006', 'Theory', 'Emergent neutrality: clumps of similar species.'],
    ],
    prompts: [
      'List the assumptions of neutral theory. Which are most often violated, and does that matter?',
      'What is θ, how is it estimated, and how does it relate to Fisher’s α?',
      'Why is fitting a species abundance distribution weak evidence for neutrality?',
      'Explain neutral theory’s value as a null model, with an example from your field.',
    ],
  },
  syn: {
    vellend: [
      ['Selection', 'Natural selection', 'Niches, competition, predation, stabilizing and equalizing mechanisms, species sorting'],
      ['Ecological drift', 'Genetic drift', 'Demographic stochasticity, small populations, neutral theory, island extinction'],
      ['Dispersal', 'Gene flow', 'Island colonization, rescue effect, metapopulations, mass effects'],
      ['Speciation', 'Mutation', 'Point speciation (θ), in-situ radiation on remote islands, regional pool'],
    ],
    answers: [
      ['Why is a Type II functional response destabilizing?', 'Per-capita predation risk, f(N)/N = a/(1 + ahN), falls as prey density rises, so predation weakens as prey increase: inverse density dependence that amplifies fluctuations.'],
      ['Why does the species with the lowest R* win?', 'At equilibrium each consumer holds the resource at its own R*. The species with the lower R* depresses the resource below the other’s break-even level, so the competitor’s growth becomes negative (single limiting resource, well-mixed, equilibrium conditions).'],
      ['Why don’t empty patches mean habitat is unimportant?', 'In colonization–extinction dynamics a fraction of suitable patches (e/c in the Levins model) is always empty. Those patches are needed for recolonization; destroying them lowers p* and can cross the extinction threshold.'],
      ['Stabilizing vs equalizing mechanisms?', 'Stabilizing mechanisms (niche differences) make intraspecific limitation exceed interspecific limitation and give rare species an advantage. Equalizing mechanisms shrink average fitness differences. Only stabilizing mechanisms create a rare-species advantage.'],
      ['How do the four paradigms differ?', 'Patch dynamics: homogeneous patches, competition–colonization trade-off. Species sorting: heterogeneous patches, moderate dispersal, composition tracks environment. Mass effects: heterogeneous patches, high dispersal, source–sink spillover. Neutral: equivalent species, drift and dispersal limitation.'],
      ['What does θ measure?', 'θ = 2J<sub>M</sub>ν, the product of metacommunity size and speciation rate. It sets regional richness and evenness under neutrality and equals Fisher’s α of the log-series.'],
    ],
  },
};

export const REFERENCES = [
  'Adler, P.B., HilleRisLambers, J. & Levine, J.M. (2007) A niche for neutrality. <i>Ecology Letters</i> 10: 95–104.',
  'Allee, W.C. (1931) <i>Animal Aggregations: A Study in General Sociology</i>. University of Chicago Press.',
  'Baselga, A. (2010) Partitioning the turnover and nestedness components of beta diversity. <i>Global Ecology and Biogeography</i> 19: 134–143.',
  'Borcard, D., Legendre, P. & Drapeau, P. (1992) Partialling out the spatial component of ecological variation. <i>Ecology</i> 73: 1045–1055.',
  'Brown, J.H. & Kodric-Brown, A. (1977) Turnover rates in insular biogeography: effect of immigration on extinction. <i>Ecology</i> 58: 445–449.',
  'Charnov, E.L. (1976) Optimal foraging, the marginal value theorem. <i>Theoretical Population Biology</i> 9: 129–136.',
  'Chase, J.M. & Leibold, M.A. (2003) <i>Ecological Niches: Linking Classical and Contemporary Approaches</i>. University of Chicago Press.',
  'Chesson, P. (2000) Mechanisms of maintenance of species diversity. <i>Annual Review of Ecology and Systematics</i> 31: 343–366.',
  'Comita, L.S. et al. (2010) Asymmetric density dependence shapes species abundances in a tropical tree community. <i>Science</i> 329: 330–332.',
  'Condit, R. et al. (2002) Beta-diversity in tropical forest trees. <i>Science</i> 295: 666–669.',
  'Connell, J.H. (1961) The influence of interspecific competition and other factors on the distribution of the barnacle <i>Chthamalus stellatus</i>. <i>Ecology</i> 42: 710–723.',
  'Connell, J.H. (1971) On the role of natural enemies in preventing competitive exclusion in some marine animals and in rain forest trees. In <i>Dynamics of Populations</i> (eds den Boer & Gradwell). PUDOC, Wageningen.',
  'Connell, J.H. (1980) Diversity and the coevolution of competitors, or the ghost of competition past. <i>Oikos</i> 35: 131–138.',
  'Cottenie, K. (2005) Integrating environmental and spatial processes in ecological community dynamics. <i>Ecology Letters</i> 8: 1175–1182.',
  'Crooks, K.R. & Soulé, M.E. (1999) Mesopredator release and avifaunal extinctions in a fragmented system. <i>Nature</i> 400: 563–566.',
  'Crouse, D.T., Crowder, L.B. & Caswell, H. (1987) A stage-based population model for loggerhead sea turtles and implications for conservation. <i>Ecology</i> 68: 1412–1423.',
  'Darlington, P.J. (1957) <i>Zoogeography: The Geographical Distribution of Animals</i>. Wiley.',
  'Diamond, J.M. (1975) The island dilemma: lessons of modern biogeographic studies for the design of natural reserves. <i>Biological Conservation</i> 7: 129–146.',
  'Elton, C.S. (1927) <i>Animal Ecology</i>. Sidgwick & Jackson.',
  'Estes, J.A., Tinker, M.T., Williams, T.M. & Doak, D.F. (1998) Killer whale predation on sea otters linking oceanic and nearshore ecosystems. <i>Science</i> 282: 473–476.',
  'Fisher, R.A., Corbet, A.S. & Williams, C.B. (1943) The relation between the number of species and the number of individuals in a random sample of an animal population. <i>Journal of Animal Ecology</i> 12: 42–58.',
  'Gause, G.F. (1934) <i>The Struggle for Existence</i>. Williams & Wilkins.',
  'Gilpin, M.E. & Soulé, M.E. (1986) Minimum viable populations: processes of species extinction. In <i>Conservation Biology: The Science of Scarcity and Diversity</i> (ed. Soulé). Sinauer.',
  'Grant, P.R. & Grant, B.R. (2006) Evolution of character displacement in Darwin’s finches. <i>Science</i> 313: 224–226.',
  'Grant, P.R. (1986) <i>Ecology and Evolution of Darwin\u2019s Finches</i>. Princeton University Press.',
  'Grime, J.P. (1977) Evidence for the existence of three primary strategies in plants and its relevance to ecological and evolutionary theory. <i>American Naturalist</i> 111: 1169–1194.',
  'Grinnell, J. (1917) The niche-relationships of the California thrasher. <i>The Auk</i> 34: 427–433.',
  'Hairston, N.G., Smith, F.E. & Slobodkin, L.B. (1960) Community structure, population control, and competition. <i>American Naturalist</i> 94: 421–425.',
  'Hansen, S.R. & Hubbell, S.P. (1980) Single-nutrient microbial competition: qualitative agreement between experimental and theoretically forecast outcomes. <i>Science</i> 207: 1491–1493.',
  'Hanski, I. (1994) A practical model of metapopulation dynamics. <i>Journal of Animal Ecology</i> 63: 151–162.',
  'Hanski, I. (1998) Metapopulation dynamics. <i>Nature</i> 396: 41–49.',
  'Harms, K.E., Wright, S.J., Calderón, O., Hernández, A. & Herre, E.A. (2000) Pervasive density-dependent recruitment enhances seedling diversity in a tropical forest. <i>Nature</i> 404: 493–495.',
  'Harrison, S. (1991) Local extinction in a metapopulation context: an empirical evaluation. <i>Biological Journal of the Linnean Society</i> 42: 73–88.',
  'Holling, C.S. (1959) Some characteristics of simple types of predation and parasitism. <i>Canadian Entomologist</i> 91: 385–398.',
  'Holt, R.D. (1977) Predation, apparent competition, and the structure of prey communities. <i>Theoretical Population Biology</i> 12: 197–229.',
  'Hubbell, S.P. (2001) <i>The Unified Neutral Theory of Biodiversity and Biogeography</i>. Princeton University Press.',
  'Huffaker, C.B. (1958) Experimental studies on predation: dispersion factors and predator–prey oscillations. <i>Hilgardia</i> 27: 343–383.',
  'Hutchinson, G.E. (1948) Circular causal systems in ecology. <i>Annals of the New York Academy of Sciences</i> 50: 221–246.',
  'Hutchinson, G.E. (1957) Concluding remarks. <i>Cold Spring Harbor Symposia on Quantitative Biology</i> 22: 415–427.',
  'Hutchinson, G.E. (1959) Homage to Santa Rosalia, or why are there so many kinds of animals? <i>American Naturalist</i> 93: 145–159.',
  'Hutchinson, G.E. (1961) The paradox of the plankton. <i>American Naturalist</i> 95: 137–145.',
  'Hutchinson, G.E. (1965) <i>The Ecological Theater and the Evolutionary Play</i>. Yale University Press.',
  'Janzen, D.H. (1970) Herbivores and the number of tree species in tropical forests. <i>American Naturalist</i> 104: 501–528.',
  'Jones, C.G., Lawton, J.H. & Shachak, M. (1994) Organisms as ecosystem engineers. <i>Oikos</i> 69: 373–386.',
  'Kimura, M. (1968) Evolutionary rate at the molecular level. <i>Nature</i> 217: 624–626.',
  'Kraft, N.J.B. et al. (2015) Community assembly, coexistence and the environmental filtering metaphor. <i>Functional Ecology</i> 29: 592–599.',
  'Krebs, C.J. et al. (1995) Impact of food and predation on the snowshoe hare cycle. <i>Science</i> 269: 1112–1115.',
  'Lack, D. (1947) <i>Darwin’s Finches</i>. Cambridge University Press.',
  'Lande, R. (1987) Extinction thresholds in demographic models of territorial populations. <i>American Naturalist</i> 130: 624–635.',
  'Laundré, J.W., Hernández, L. & Altendorf, K.B. (2001) Wolves, elk, and bison: reestablishing the “landscape of fear” in Yellowstone National Park, U.S.A. <i>Canadian Journal of Zoology</i> 79: 1401–1409.',
  'Leibold, M.A. & Chase, J.M. (2018) <i>Metacommunity Ecology</i>. Princeton University Press.',
  'Leibold, M.A. et al. (2004) The metacommunity concept: a framework for multi-scale community ecology. <i>Ecology Letters</i> 7: 601–613.',
  'Levins, R. (1969) Some demographic and genetic consequences of environmental heterogeneity for biological control. <i>Bulletin of the Entomological Society of America</i> 15: 237–240.',
  'Lomolino, M.V. (1990) The target area hypothesis: the influence of island area on immigration rates of non-volant mammals. <i>Oikos</i> 57: 297–300.',
  'Lotka, A.J. (1925) <i>Elements of Physical Biology</i>. Williams & Wilkins.',
  'MacArthur, R.H. & Levins, R. (1967) The limiting similarity, convergence, and divergence of coexisting species. <i>American Naturalist</i> 101: 377–385.',
  'MacArthur, R.H. & Wilson, E.O. (1963) An equilibrium theory of insular zoogeography. <i>Evolution</i> 17: 373–387.',
  'MacArthur, R.H. & Wilson, E.O. (1967) <i>The Theory of Island Biogeography</i>. Princeton University Press.',
  'MacArthur, R.H. (1958) Population ecology of some warblers of northeastern coniferous forests. <i>Ecology</i> 39: 599–619.',
  'May, R.M. (1976) Simple mathematical models with very complicated dynamics. <i>Nature</i> 261: 459–467.',
  'McGill, B.J. (2003) A test of the unified neutral theory of biodiversity. <i>Nature</i> 422: 881–885.',
  'Moran, P.A.P. (1953) The statistical analysis of the Canadian lynx cycle. II. Synchronization and meteorology. <i>Australian Journal of Zoology</i> 1: 291–298.',
  'Mouquet, N. & Loreau, M. (2003) Community patterns in source–sink metacommunities. <i>American Naturalist</i> 162: 544–557.',
  'Newmark, W.D. (1987) A land-bridge island perspective on mammalian extinctions in western North American parks. <i>Nature</i> 325: 430–432.',
  'Nicholson, A.J. & Bailey, V.A. (1935) The balance of animal populations. Part I. <i>Proceedings of the Zoological Society of London</i> 105: 551–598.',
  'Nicholson, A.J. (1954) An outline of the dynamics of animal populations. <i>Australian Journal of Zoology</i> 2: 9–65.',
  'Odling-Smee, F.J., Laland, K.N. & Feldman, M.W. (2003) <i>Niche Construction: The Neglected Process in Evolution</i>. Princeton University Press.',
  'Odum, E.P. (1959) <i>Fundamentals of Ecology</i>, 2nd edn. Saunders.',
  'Paine, R.T. (1966) Food web complexity and species diversity. <i>American Naturalist</i> 100: 65–75.',
  'Paine, R.T. (1969) A note on trophic complexity and community stability. <i>American Naturalist</i> 103: 91–93.',
  'Park, T. (1954) Experimental studies of interspecies competition. II. Temperature, humidity, and competition in two species of <i>Tribolium</i>. <i>Physiological Zoology</i> 27: 177–238.',
  'Pianka, E.R. (1970) On r- and K-selection. <i>American Naturalist</i> 104: 592–597.',
  'Power, M.E. et al. (1996) Challenges in the quest for keystones. <i>BioScience</i> 46: 609–620.',
  'Preston, F.W. (1948) The commonness, and rarity, of species. <i>Ecology</i> 29: 254–283.',
  'Preston, F.W. (1962) The canonical distribution of commonness and rarity. <i>Ecology</i> 43: 185–215, 410–432.',
  'Pulliam, H.R. (1988) Sources, sinks, and population regulation. <i>American Naturalist</i> 132: 652–661.',
  'Rosenzweig, M.L. & MacArthur, R.H. (1963) Graphical representation and stability conditions of predator–prey interactions. <i>American Naturalist</i> 97: 209–223.',
  'Rosenzweig, M.L. (1971) Paradox of enrichment: destabilization of exploitation ecosystems in ecological time. <i>Science</i> 171: 385–387.',
  'Rosindell, J., Hubbell, S.P. & Etienne, R.S. (2011) The unified neutral theory of biodiversity and biogeography at age ten. <i>Trends in Ecology & Evolution</i> 26: 340–348.',
  'Scheffer, M. & van Nes, E.H. (2006) Self-organized similarity, the evolutionary emergence of groups of similar species. <i>PNAS</i> 103: 6230–6235.',
  'Schlaepfer, M.A., Runge, M.C. & Sherman, P.W. (2002) Ecological and evolutionary traps. <i>Trends in Ecology & Evolution</i> 17: 474–480.',
  'Schluter, D. & McPhail, J.D. (1992) Ecological character displacement and speciation in sticklebacks. <i>American Naturalist</i> 140: 85–108.',
  'Schoener, T.W. (1983) Field experiments on interspecific competition. <i>American Naturalist</i> 122: 240–285.',
  'Shaffer, M.L. (1981) Minimum population sizes for species conservation. <i>BioScience</i> 31: 131–134.',
  'Sheriff, M.J., Krebs, C.J. & Boonstra, R. (2009) The sensitive hare: sublethal effects of predator stress on reproduction in snowshoe hares. <i>Journal of Animal Ecology</i> 78: 1249–1258.',
  'Simberloff, D. & Boecklen, W. (1981) Santa Rosalia reconsidered: size ratios and competition. <i>Evolution</i> 35: 1206–1228.',
  'Simberloff, D.S. & Abele, L.G. (1976) Island biogeography theory and conservation practice. <i>Science</i> 191: 285–286.',
  'Simberloff, D.S. & Wilson, E.O. (1969) Experimental zoogeography of islands: the colonization of empty islands. <i>Ecology</i> 50: 278–296.',
  'Simberloff, D.S. & Wilson, E.O. (1970) Experimental zoogeography of islands: a two-year record of colonization. <i>Ecology</i> 51: 934–937.',
  'Soberón, J. & Peterson, A.T. (2005) Interpretation of models of fundamental ecological niches and species’ distributional areas. <i>Biodiversity Informatics</i> 2: 1–10.',
  'Tilman, D. & Wedin, D. (1991) Dynamics of nitrogen competition between successional grasses. <i>Ecology</i> 72: 1038–1049.',
  'Tilman, D. (1977) Resource competition between planktonic algae: an experimental and theoretical approach. <i>Ecology</i> 58: 338–348.',
  'Tilman, D. (1982) <i>Resource Competition and Community Structure</i>. Princeton University Press.',
  'Tilman, D. (1994) Competition and biodiversity in spatially structured habitats. <i>Ecology</i> 75: 2–16.',
  'Tilman, D., May, R.M., Lehman, C.L. & Nowak, M.A. (1994) Habitat destruction and the extinction debt. <i>Nature</i> 371: 65–66.',
  'Vellend, M. (2010) Conceptual synthesis in community ecology. <i>Quarterly Review of Biology</i> 85: 183–206.',
  'Vellend, M. (2016) <i>The Theory of Ecological Communities</i>. Princeton University Press.',
  'Volkov, I., Banavar, J.R., Hubbell, S.P. & Maritan, A. (2003) Neutral theory and relative species abundance in ecology. <i>Nature</i> 424: 1035–1037.',
  'Volterra, V. (1926) Fluctuations in the abundance of a species considered mathematically. <i>Nature</i> 118: 558–560.',
  'Wedin, D. & Tilman, D. (1993) Competition among grasses along a nitrogen gradient: initial conditions and mechanisms of competition. <i>Ecological Monographs</i> 63: 199–229.',
  'Whittaker, R.H. (1960) Vegetation of the Siskiyou Mountains, Oregon and California. <i>Ecological Monographs</i> 30: 279–338.',
  'Whittaker, R.H. (1972) Evolution and measurement of species diversity. <i>Taxon</i> 21: 213–251.',
  'Whittaker, R.J., Triantis, K.A. & Ladle, R.J. (2008) A general dynamic theory of oceanic island biogeography. <i>Journal of Biogeography</i> 35: 977–994.',
  'Zanette, L.Y., White, A.F., Allen, M.C. & Clinchy, M. (2011) Perceived predation risk reduces the number of offspring songbirds produce per year. <i>Science</i> 334: 1398–1401.',
];
